### ISSUE TITLE
themes don't work

### ISSUE THREAD

**Issue by EngineerRunner** [SnarpleDev/Snazzle#21]
after the forums update, themes now don't work. if you change the theme in settings, it does nothing.

**Comment by Darth-Ness** [comment]
I have an idea that I'm working on my local branch.

**Comment by EngineerRunner** [comment]
here's a working version to compare against if anybody needs it: https://github.com/redstone-scratch/Snazzle/archive/82741cb91acde2fbc688aaaa259812592efcc98b.zip
