### ISSUE TITLE
Adding AI tools to Snazzle

### ISSUE THREAD

**Issue by NotFenixio** [SnarpleDev/Snazzle#59]
So, i've read [this](https://www.discourse.org/plugins/ai.html) article from Discourse, an open source forum software, that says you can enable certain AI features via the OpenAI API.

So, i was curious... Why don't we do the same?

My idea is to add some tools like Summarization.

Attention, we would only add an implementation of these tools but we would not provide an example of them (we ain't getting broke).

What do you think?

**Comment by redstone-dev** [comment]
Summarization would be good for longer posts, but I think it would be unnecessary bloat as of now. We could revisit it later.
